// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
	"fmt"
	"io"
	"sync/atomic"

	"github.com/go-sql-driver/mysql"
	"github.com/hexon/mysqltsv"
)

var readerHandlerSequenceForBulkInsertUsers uint32 = 1

func convertRowsForBulkInsertUsers(w *io.PipeWriter, arg []BulkInsertUsersParams) {
	e := mysqltsv.NewEncoder(w, 2, nil)
	for _, row := range arg {
		e.AppendString(row.Name)
		e.AppendString(row.Email)
	}
	w.CloseWithError(e.Close())
}

type bulkInsertUsersQuery struct {
	rows []BulkInsertUsersParams
}

func (q bulkInsertUsersQuery) SQL() string { return "" }
func (q bulkInsertUsersQuery) Args() []any { return nil }

func (q bulkInsertUsersQuery) Do(ctx context.Context, db DBTX) (int64, error) {
	pr, pw := io.Pipe()
	defer pr.Close()
	rh := fmt.Sprintf("BulkInsertUsers_%d", atomic.AddUint32(&readerHandlerSequenceForBulkInsertUsers, 1))
	mysql.RegisterReaderHandler(rh, func() io.Reader { return pr })
	defer mysql.DeregisterReaderHandler(rh)
	go convertRowsForBulkInsertUsers(pw, q.rows)
	// The string interpolation is necessary because LOAD DATA INFILE requires
	// the file name to be given as a literal string.
	result, err := db.ExecContext(ctx, fmt.Sprintf("LOAD DATA LOCAL INFILE '%s' INTO TABLE `users` %s (name, email)", "Reader::"+rh, mysqltsv.Escaping))
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

// BulkInsertUsers uses MySQL's LOAD DATA LOCAL INFILE and is not atomic.
//
// Errors and duplicate keys are treated as warnings and insertion will
// continue, even without an error for some cases.  Use this in a transaction
// and use SHOW WARNINGS to check for any problems and roll back if you want to.
//
// Check the documentation for more information:
// https://dev.mysql.com/doc/refman/8.0/en/load-data.html#load-data-error-handling
func BulkInsertUsers(arg []BulkInsertUsersParams) Query[int64] {
	return bulkInsertUsersQuery{rows: arg}
}
