// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

type CountUsersQuery struct {
	ex     QueryExecutor
	result int64
}

func (q *CountUsersQuery) SQL() string {
	return countUsers
}

func (q *CountUsersQuery) Args() []any {
	return nil
}

func (q *CountUsersQuery) Scan(row *sql.Row) error {
	return row.Scan(&q.result)
}

func (q *CountUsersQuery) Result() int64 {
	return q.result
}

func (q *CountUsersQuery) SetResult(result int64) {
	q.result = result
}
func (q *CountUsersQuery) Eval(ctx context.Context) (int64, error) {
	if err := q.ex.Execute(ctx, q); err != nil {
		var zero int64
		return zero, err
	}
	return q.Result(), nil
}

func NewCountUsersQuery(ex QueryExecutor) *CountUsersQuery {
	return &CountUsersQuery{ex: ex}
}
func ExpectCountUsers(result int64, err error) Step {
	return Step{
		SQL:  countUsers,
		Args: nil,
		Apply: func(q Query) error {
			q.(*CountUsersQuery).SetResult(result)
			return err
		},
	}
}

const createPost = `-- name: CreatePost :execlastid
INSERT INTO posts (author_id, title, body)
VALUES (?, ?, ?)
`

type CreatePostParams struct {
	AuthorID int64  `json:"author_id"`
	Title    string `json:"title"`
	Body     string `json:"body"`
}

type CreatePostQuery struct {
	ex           QueryExecutor
	arg          CreatePostParams
	lastID       int64
	rowsAffected int64
}

func (q *CreatePostQuery) SQL() string {
	return createPost
}

func (q *CreatePostQuery) Args() []any {
	return []any{q.arg.AuthorID, q.arg.Title, q.arg.Body}
}

func (q *CreatePostQuery) SetLastInsertID(n int64) {
	q.lastID = n
}

func (q *CreatePostQuery) SetRowsAffected(n int64) {
	q.rowsAffected = n
}
func (q *CreatePostQuery) Eval(ctx context.Context, arg CreatePostParams) (int64, error) {
	q.arg = arg
	if err := q.ex.Execute(ctx, q); err != nil {
		return 0, err
	}
	return q.lastID, nil
}

func NewCreatePostQuery(ex QueryExecutor) *CreatePostQuery {
	return &CreatePostQuery{ex: ex}
}
func ExpectCreatePost(arg CreatePostParams, lastID int64, err error) Step {
	return Step{
		SQL:  createPost,
		Args: []any{arg.AuthorID, arg.Title, arg.Body},
		Apply: func(q Query) error {
			q.(*CreatePostQuery).SetLastInsertID(lastID)
			return err
		},
	}
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (name, email)
VALUES (?, ?)
`

type CreateUserQuery struct {
	ex    QueryExecutor
	name  string
	email string
}

func (q *CreateUserQuery) SQL() string {
	return createUser
}

func (q *CreateUserQuery) Args() []any {
	return []any{q.name, q.email}
}

func NewCreateUserQuery(ex QueryExecutor) *CreateUserQuery {
	return &CreateUserQuery{ex: ex}
}

const createUserGetID = `-- name: CreateUserGetID :execlastid
INSERT INTO users (name, email)
VALUES (?, ?)
`

type CreateUserGetIDQuery struct {
	ex           QueryExecutor
	name         string
	email        string
	lastID       int64
	rowsAffected int64
}

func (q *CreateUserGetIDQuery) SQL() string {
	return createUserGetID
}

func (q *CreateUserGetIDQuery) Args() []any {
	return []any{q.name, q.email}
}

func (q *CreateUserGetIDQuery) SetLastInsertID(n int64) {
	q.lastID = n
}

func (q *CreateUserGetIDQuery) SetRowsAffected(n int64) {
	q.rowsAffected = n
}
func (q *CreateUserGetIDQuery) Eval(ctx context.Context, name string, email string) (int64, error) {
	q.name = name
	q.email = email
	if err := q.ex.Execute(ctx, q); err != nil {
		return 0, err
	}
	return q.lastID, nil
}

func NewCreateUserGetIDQuery(ex QueryExecutor) *CreateUserGetIDQuery {
	return &CreateUserGetIDQuery{ex: ex}
}
func ExpectCreateUserGetID(name string, email string, lastID int64, err error) Step {
	return Step{
		SQL:  createUserGetID,
		Args: []any{name, email},
		Apply: func(q Query) error {
			q.(*CreateUserGetIDQuery).SetLastInsertID(lastID)
			return err
		},
	}
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = ?
`

type DeleteUserQuery struct {
	ex           QueryExecutor
	id           int64
	rowsAffected int64
}

func (q *DeleteUserQuery) SQL() string {
	return deleteUser
}

func (q *DeleteUserQuery) Args() []any {
	return []any{q.id}
}

func (q *DeleteUserQuery) SetRowsAffected(n int64) {
	q.rowsAffected = n
}
func (q *DeleteUserQuery) Eval(ctx context.Context, id int64) error {
	q.id = id
	return q.ex.Execute(ctx, q)
}

func NewDeleteUserQuery(ex QueryExecutor) *DeleteUserQuery {
	return &DeleteUserQuery{ex: ex}
}
func ExpectDeleteUser(id int64, err error) Step {
	return Step{
		SQL:  deleteUser,
		Args: []any{id},
		Apply: func(q Query) error {
			return err
		},
	}
}

const getPostWithAuthor = `-- name: GetPostWithAuthor :one
SELECT posts.id, posts.author_id, posts.title, posts.body, posts.created_at, users.id, users.name, users.email, users.created_at
FROM posts
JOIN users ON users.id = posts.author_id
WHERE posts.id = ?
`

type GetPostWithAuthorRow struct {
	Post Post `json:"post"`
	User User `json:"user"`
}

type GetPostWithAuthorQuery struct {
	ex     QueryExecutor
	id     int64
	result GetPostWithAuthorRow
}

func (q *GetPostWithAuthorQuery) SQL() string {
	return getPostWithAuthor
}

func (q *GetPostWithAuthorQuery) Args() []any {
	return []any{q.id}
}

func (q *GetPostWithAuthorQuery) Scan(row *sql.Row) error {
	return row.Scan(
		&q.result.Post.ID,
		&q.result.Post.AuthorID,
		&q.result.Post.Title,
		&q.result.Post.Body,
		&q.result.Post.CreatedAt,
		&q.result.User.ID,
		&q.result.User.Name,
		&q.result.User.Email,
		&q.result.User.CreatedAt,
	)
}

func (q *GetPostWithAuthorQuery) Result() GetPostWithAuthorRow {
	return q.result
}

func (q *GetPostWithAuthorQuery) SetResult(result GetPostWithAuthorRow) {
	q.result = result
}
func (q *GetPostWithAuthorQuery) Eval(ctx context.Context, id int64) (GetPostWithAuthorRow, error) {
	q.id = id
	if err := q.ex.Execute(ctx, q); err != nil {
		var zero GetPostWithAuthorRow
		return zero, err
	}
	return q.Result(), nil
}

func NewGetPostWithAuthorQuery(ex QueryExecutor) *GetPostWithAuthorQuery {
	return &GetPostWithAuthorQuery{ex: ex}
}
func ExpectGetPostWithAuthor(id int64, result GetPostWithAuthorRow, err error) Step {
	return Step{
		SQL:  getPostWithAuthor,
		Args: []any{id},
		Apply: func(q Query) error {
			q.(*GetPostWithAuthorQuery).SetResult(result)
			return err
		},
	}
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, created_at FROM users
WHERE id = ?
`

type GetUserQuery struct {
	ex     QueryExecutor
	id     int64
	result User
}

func (q *GetUserQuery) SQL() string {
	return getUser
}

func (q *GetUserQuery) Args() []any {
	return []any{q.id}
}

func (q *GetUserQuery) Scan(row *sql.Row) error {
	return row.Scan(
		&q.result.ID,
		&q.result.Name,
		&q.result.Email,
		&q.result.CreatedAt,
	)
}

func (q *GetUserQuery) Result() User {
	return q.result
}

func (q *GetUserQuery) SetResult(result User) {
	q.result = result
}
func (q *GetUserQuery) Eval(ctx context.Context, id int64) (User, error) {
	q.id = id
	if err := q.ex.Execute(ctx, q); err != nil {
		var zero User
		return zero, err
	}
	return q.Result(), nil
}

func NewGetUserQuery(ex QueryExecutor) *GetUserQuery {
	return &GetUserQuery{ex: ex}
}
func ExpectGetUser(id int64, result User, err error) Step {
	return Step{
		SQL:  getUser,
		Args: []any{id},
		Apply: func(q Query) error {
			q.(*GetUserQuery).SetResult(result)
			return err
		},
	}
}

const listPostsWithAuthor = `-- name: ListPostsWithAuthor :many
SELECT posts.id, posts.author_id, posts.title, posts.body, posts.created_at, users.id, users.name, users.email, users.created_at
FROM posts
JOIN users ON users.id = posts.author_id
ORDER BY posts.created_at DESC
`

type ListPostsWithAuthorRow struct {
	Post Post `json:"post"`
	User User `json:"user"`
}

type ListPostsWithAuthorQuery struct {
	ex      QueryExecutor
	results []ListPostsWithAuthorRow
}

func (q *ListPostsWithAuthorQuery) SQL() string {
	return listPostsWithAuthor
}

func (q *ListPostsWithAuthorQuery) Args() []any {
	return nil
}

func (q *ListPostsWithAuthorQuery) ScanRow(row *sql.Rows) error {
	var i ListPostsWithAuthorRow
	if err := row.Scan(
		&i.Post.ID,
		&i.Post.AuthorID,
		&i.Post.Title,
		&i.Post.Body,
		&i.Post.CreatedAt,
		&i.User.ID,
		&i.User.Name,
		&i.User.Email,
		&i.User.CreatedAt,
	); err != nil {
		return err
	}
	q.results = append(q.results, i)
	return nil
}

func (q *ListPostsWithAuthorQuery) Results() []ListPostsWithAuthorRow {
	return q.results
}

func (q *ListPostsWithAuthorQuery) SetResults(results []ListPostsWithAuthorRow) {
	q.results = results
}
func (q *ListPostsWithAuthorQuery) Eval(ctx context.Context) ([]ListPostsWithAuthorRow, error) {
	q.results = nil
	if err := q.ex.Execute(ctx, q); err != nil {
		return nil, err
	}
	return q.Results(), nil
}

func NewListPostsWithAuthorQuery(ex QueryExecutor) *ListPostsWithAuthorQuery {
	return &ListPostsWithAuthorQuery{ex: ex}
}
func ExpectListPostsWithAuthor(results []ListPostsWithAuthorRow, err error) Step {
	return Step{
		SQL:  listPostsWithAuthor,
		Args: nil,
		Apply: func(q Query) error {
			q.(*ListPostsWithAuthorQuery).SetResults(results)
			return err
		},
	}
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, created_at FROM users
ORDER BY created_at DESC
`

type ListUsersQuery struct {
	ex      QueryExecutor
	results []User
}

func (q *ListUsersQuery) SQL() string {
	return listUsers
}

func (q *ListUsersQuery) Args() []any {
	return nil
}

func (q *ListUsersQuery) ScanRow(row *sql.Rows) error {
	var i User
	if err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
	); err != nil {
		return err
	}
	q.results = append(q.results, i)
	return nil
}

func (q *ListUsersQuery) Results() []User {
	return q.results
}

func (q *ListUsersQuery) SetResults(results []User) {
	q.results = results
}
func (q *ListUsersQuery) Eval(ctx context.Context) ([]User, error) {
	q.results = nil
	if err := q.ex.Execute(ctx, q); err != nil {
		return nil, err
	}
	return q.Results(), nil
}

func NewListUsersQuery(ex QueryExecutor) *ListUsersQuery {
	return &ListUsersQuery{ex: ex}
}
func ExpectListUsers(results []User, err error) Step {
	return Step{
		SQL:  listUsers,
		Args: nil,
		Apply: func(q Query) error {
			q.(*ListUsersQuery).SetResults(results)
			return err
		},
	}
}

const updateUserEmail = `-- name: UpdateUserEmail :execresult
UPDATE users
SET email = ?
WHERE id = ?
`

type UpdateUserEmailQuery struct {
	ex    QueryExecutor
	email string
	iD    int64
}

func (q *UpdateUserEmailQuery) SQL() string {
	return updateUserEmail
}

func (q *UpdateUserEmailQuery) Args() []any {
	return []any{q.email, q.iD}
}

func NewUpdateUserEmailQuery(ex QueryExecutor) *UpdateUserEmailQuery {
	return &UpdateUserEmailQuery{ex: ex}
}

const updateUserName = `-- name: UpdateUserName :execrows
UPDATE users
SET name = ?
WHERE id = ?
`

type UpdateUserNameQuery struct {
	ex           QueryExecutor
	name         string
	iD           int64
	rowsAffected int64
}

func (q *UpdateUserNameQuery) SQL() string {
	return updateUserName
}

func (q *UpdateUserNameQuery) Args() []any {
	return []any{q.name, q.iD}
}

func (q *UpdateUserNameQuery) SetRowsAffected(n int64) {
	q.rowsAffected = n
}
func (q *UpdateUserNameQuery) Eval(ctx context.Context, name string, iD int64) (int64, error) {
	q.name = name
	q.iD = iD
	if err := q.ex.Execute(ctx, q); err != nil {
		return 0, err
	}
	return q.rowsAffected, nil
}

func NewUpdateUserNameQuery(ex QueryExecutor) *UpdateUserNameQuery {
	return &UpdateUserNameQuery{ex: ex}
}
func ExpectUpdateUserName(name string, iD int64, rowsAffected int64, err error) Step {
	return Step{
		SQL:  updateUserName,
		Args: []any{name, iD},
		Apply: func(q Query) error {
			q.(*UpdateUserNameQuery).SetRowsAffected(rowsAffected)
			return err
		},
	}
}
