// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"

	"github.com/jackc/pgx/v5"
)

type BulkInsertUsersParams struct {
	Name  string `db:"name" json:"name"`
	Email string `db:"email" json:"email"`
}

// iteratorForBulkInsertUsers implements pgx.CopyFromSource.
type iteratorForBulkInsertUsers struct {
	rows                 []BulkInsertUsersParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkInsertUsers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkInsertUsers) Values() ([]any, error) {
	return []any{
		r.rows[0].Name,
		r.rows[0].Email,
	}, nil
}

func (r iteratorForBulkInsertUsers) Err() error {
	return nil
}

var _ pgx.CopyFromSource = (*iteratorForBulkInsertUsers)(nil)

type bulkInsertUsersQuery struct {
	rows []BulkInsertUsersParams
}

func (q bulkInsertUsersQuery) SQL() string { return "" }
func (q bulkInsertUsersQuery) Args() []any { return nil }

func (q bulkInsertUsersQuery) Do(ctx context.Context, db DBTX) (int64, error) {
	return db.CopyFrom(ctx, []string{"users"}, []string{"name", "email"}, &iteratorForBulkInsertUsers{rows: q.rows})
}

func BulkInsertUsers(arg []BulkInsertUsersParams) Query[int64] {
	return bulkInsertUsersQuery{rows: arg}
}
