// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

type CountUsersQuery struct {
	ex     QueryExecutor
	Result int64
}

func (q *CountUsersQuery) SQL() string {
	return countUsers
}

func (q *CountUsersQuery) Args() []any {
	return nil
}

func (q *CountUsersQuery) Scan(row pgx.Row) error {
	return row.Scan(&q.Result)
}

func (q *CountUsersQuery) SetResult(result int64) {
	q.Result = result
}
func (q *CountUsersQuery) Eval(ctx context.Context) (int64, error) {
	if err := q.ex.Execute(ctx, q); err != nil {
		var zero int64
		return zero, err
	}
	return q.Result, nil
}

func NewCountUsersQuery(ex QueryExecutor) *CountUsersQuery {
	return &CountUsersQuery{ex: ex}
}
func ExpectCountUsers(result int64, err error) Step {
	return Step{
		SQL:  countUsers,
		Args: nil,
		Apply: func(q Query) error {
			q.(*CountUsersQuery).SetResult(result)
			return err
		},
	}
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (author_id, title, body)
VALUES ($1, $2, $3)
RETURNING id, author_id, title, body, created_at
`

type CreatePostParams struct {
	AuthorID int64  `db:"author_id" json:"author_id"`
	Title    string `db:"title" json:"title"`
	Body     string `db:"body" json:"body"`
}

type CreatePostQuery struct {
	ex     QueryExecutor
	arg    CreatePostParams
	Result Post
}

func (q *CreatePostQuery) SQL() string {
	return createPost
}

func (q *CreatePostQuery) Args() []any {
	return []any{q.arg.AuthorID, q.arg.Title, q.arg.Body}
}

func (q *CreatePostQuery) Scan(row pgx.Row) error {
	return row.Scan(
		&q.Result.ID,
		&q.Result.AuthorID,
		&q.Result.Title,
		&q.Result.Body,
		&q.Result.CreatedAt,
	)
}

func (q *CreatePostQuery) SetResult(result Post) {
	q.Result = result
}
func (q *CreatePostQuery) Eval(ctx context.Context, arg CreatePostParams) (Post, error) {
	q.arg = arg
	if err := q.ex.Execute(ctx, q); err != nil {
		var zero Post
		return zero, err
	}
	return q.Result, nil
}

func NewCreatePostQuery(ex QueryExecutor) *CreatePostQuery {
	return &CreatePostQuery{ex: ex}
}
func ExpectCreatePost(arg CreatePostParams, result Post, err error) Step {
	return Step{
		SQL:  createPost,
		Args: []any{arg.AuthorID, arg.Title, arg.Body},
		Apply: func(q Query) error {
			q.(*CreatePostQuery).SetResult(result)
			return err
		},
	}
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, status)
VALUES ($1, $2, $3)
RETURNING id, name, email, status, description, created_at
`

type CreateUserParams struct {
	Name   string     `db:"name" json:"name"`
	Email  string     `db:"email" json:"email"`
	Status UserStatus `db:"status" json:"status"`
}

type CreateUserQuery struct {
	ex     QueryExecutor
	arg    CreateUserParams
	Result User
}

func (q *CreateUserQuery) SQL() string {
	return createUser
}

func (q *CreateUserQuery) Args() []any {
	return []any{q.arg.Name, q.arg.Email, q.arg.Status}
}

func (q *CreateUserQuery) Scan(row pgx.Row) error {
	return row.Scan(
		&q.Result.ID,
		&q.Result.Name,
		&q.Result.Email,
		&q.Result.Status,
		&q.Result.Description,
		&q.Result.CreatedAt,
	)
}

func (q *CreateUserQuery) SetResult(result User) {
	q.Result = result
}
func (q *CreateUserQuery) Eval(ctx context.Context, arg CreateUserParams) (User, error) {
	q.arg = arg
	if err := q.ex.Execute(ctx, q); err != nil {
		var zero User
		return zero, err
	}
	return q.Result, nil
}

func NewCreateUserQuery(ex QueryExecutor) *CreateUserQuery {
	return &CreateUserQuery{ex: ex}
}
func ExpectCreateUser(arg CreateUserParams, result User, err error) Step {
	return Step{
		SQL:  createUser,
		Args: []any{arg.Name, arg.Email, arg.Status},
		Apply: func(q Query) error {
			q.(*CreateUserQuery).SetResult(result)
			return err
		},
	}
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

type DeleteUserQuery struct {
	ex           QueryExecutor
	id           int64
	RowsAffected int64
}

func (q *DeleteUserQuery) SQL() string {
	return deleteUser
}

func (q *DeleteUserQuery) Args() []any {
	return []any{q.id}
}

func (q *DeleteUserQuery) SetRowsAffected(n int64) {
	q.RowsAffected = n
}
func (q *DeleteUserQuery) Eval(ctx context.Context, id int64) error {
	q.id = id
	return q.ex.Execute(ctx, q)
}

func NewDeleteUserQuery(ex QueryExecutor) *DeleteUserQuery {
	return &DeleteUserQuery{ex: ex}
}
func ExpectDeleteUser(id int64, err error) Step {
	return Step{
		SQL:  deleteUser,
		Args: []any{id},
		Apply: func(q Query) error {
			return err
		},
	}
}

const getPostWithAuthor = `-- name: GetPostWithAuthor :one
SELECT posts.id, posts.author_id, posts.title, posts.body, posts.created_at, users.id, users.name, users.email, users.status, users.description, users.created_at
FROM posts
JOIN users ON users.id = posts.author_id
WHERE posts.id = $1
`

type GetPostWithAuthorRow struct {
	Post Post `db:"post" json:"post"`
	User User `db:"user" json:"user"`
}

type GetPostWithAuthorQuery struct {
	ex     QueryExecutor
	id     int64
	Result GetPostWithAuthorRow
}

func (q *GetPostWithAuthorQuery) SQL() string {
	return getPostWithAuthor
}

func (q *GetPostWithAuthorQuery) Args() []any {
	return []any{q.id}
}

func (q *GetPostWithAuthorQuery) Scan(row pgx.Row) error {
	return row.Scan(
		&q.Result.Post.ID,
		&q.Result.Post.AuthorID,
		&q.Result.Post.Title,
		&q.Result.Post.Body,
		&q.Result.Post.CreatedAt,
		&q.Result.User.ID,
		&q.Result.User.Name,
		&q.Result.User.Email,
		&q.Result.User.Status,
		&q.Result.User.Description,
		&q.Result.User.CreatedAt,
	)
}

func (q *GetPostWithAuthorQuery) SetResult(result GetPostWithAuthorRow) {
	q.Result = result
}
func (q *GetPostWithAuthorQuery) Eval(ctx context.Context, id int64) (GetPostWithAuthorRow, error) {
	q.id = id
	if err := q.ex.Execute(ctx, q); err != nil {
		var zero GetPostWithAuthorRow
		return zero, err
	}
	return q.Result, nil
}

func NewGetPostWithAuthorQuery(ex QueryExecutor) *GetPostWithAuthorQuery {
	return &GetPostWithAuthorQuery{ex: ex}
}
func ExpectGetPostWithAuthor(id int64, result GetPostWithAuthorRow, err error) Step {
	return Step{
		SQL:  getPostWithAuthor,
		Args: []any{id},
		Apply: func(q Query) error {
			q.(*GetPostWithAuthorQuery).SetResult(result)
			return err
		},
	}
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, status, description, created_at FROM users
WHERE id = $1
`

type GetUserQuery struct {
	ex     QueryExecutor
	id     int64
	Result User
}

func (q *GetUserQuery) SQL() string {
	return getUser
}

func (q *GetUserQuery) Args() []any {
	return []any{q.id}
}

func (q *GetUserQuery) Scan(row pgx.Row) error {
	return row.Scan(
		&q.Result.ID,
		&q.Result.Name,
		&q.Result.Email,
		&q.Result.Status,
		&q.Result.Description,
		&q.Result.CreatedAt,
	)
}

func (q *GetUserQuery) SetResult(result User) {
	q.Result = result
}
func (q *GetUserQuery) Eval(ctx context.Context, id int64) (User, error) {
	q.id = id
	if err := q.ex.Execute(ctx, q); err != nil {
		var zero User
		return zero, err
	}
	return q.Result, nil
}

func NewGetUserQuery(ex QueryExecutor) *GetUserQuery {
	return &GetUserQuery{ex: ex}
}
func ExpectGetUser(id int64, result User, err error) Step {
	return Step{
		SQL:  getUser,
		Args: []any{id},
		Apply: func(q Query) error {
			q.(*GetUserQuery).SetResult(result)
			return err
		},
	}
}

const getUserForUpdate = `-- name: GetUserForUpdate :one
SELECT id, name, email, status, description, created_at FROM users
WHERE id = $1
FOR UPDATE
`

type GetUserForUpdateQuery struct {
	ex     QueryExecutor
	id     int64
	Result User
}

func (q *GetUserForUpdateQuery) SQL() string {
	return getUserForUpdate
}

func (q *GetUserForUpdateQuery) Args() []any {
	return []any{q.id}
}

func (q *GetUserForUpdateQuery) Scan(row pgx.Row) error {
	return row.Scan(
		&q.Result.ID,
		&q.Result.Name,
		&q.Result.Email,
		&q.Result.Status,
		&q.Result.Description,
		&q.Result.CreatedAt,
	)
}

func (q *GetUserForUpdateQuery) SetResult(result User) {
	q.Result = result
}
func (q *GetUserForUpdateQuery) Eval(ctx context.Context, id int64) (User, error) {
	q.id = id
	if err := q.ex.Execute(ctx, q); err != nil {
		var zero User
		return zero, err
	}
	return q.Result, nil
}

func NewGetUserForUpdateQuery(ex QueryExecutor) *GetUserForUpdateQuery {
	return &GetUserForUpdateQuery{ex: ex}
}
func ExpectGetUserForUpdate(id int64, result User, err error) Step {
	return Step{
		SQL:  getUserForUpdate,
		Args: []any{id},
		Apply: func(q Query) error {
			q.(*GetUserForUpdateQuery).SetResult(result)
			return err
		},
	}
}

const listPostsWithAuthor = `-- name: ListPostsWithAuthor :many
SELECT posts.id, posts.author_id, posts.title, posts.body, posts.created_at, users.id, users.name, users.email, users.status, users.description, users.created_at
FROM posts
JOIN users ON users.id = posts.author_id
ORDER BY posts.created_at DESC
`

type ListPostsWithAuthorRow struct {
	Post Post `db:"post" json:"post"`
	User User `db:"user" json:"user"`
}

type ListPostsWithAuthorQuery struct {
	ex      QueryExecutor
	Results []ListPostsWithAuthorRow
}

func (q *ListPostsWithAuthorQuery) SQL() string {
	return listPostsWithAuthor
}

func (q *ListPostsWithAuthorQuery) Args() []any {
	return nil
}

func (q *ListPostsWithAuthorQuery) ScanRow(row pgx.Row) error {
	var i ListPostsWithAuthorRow
	if err := row.Scan(
		&i.Post.ID,
		&i.Post.AuthorID,
		&i.Post.Title,
		&i.Post.Body,
		&i.Post.CreatedAt,
		&i.User.ID,
		&i.User.Name,
		&i.User.Email,
		&i.User.Status,
		&i.User.Description,
		&i.User.CreatedAt,
	); err != nil {
		return err
	}
	q.Results = append(q.Results, i)
	return nil
}

func (q *ListPostsWithAuthorQuery) SetResults(results []ListPostsWithAuthorRow) {
	q.Results = results
}

func (q *ListPostsWithAuthorQuery) Eval(ctx context.Context) ([]ListPostsWithAuthorRow, error) {
	q.Results = nil
	if err := q.ex.Execute(ctx, q); err != nil {
		return nil, err
	}
	return q.Results, nil
}

func NewListPostsWithAuthorQuery(ex QueryExecutor) *ListPostsWithAuthorQuery {
	return &ListPostsWithAuthorQuery{ex: ex}
}
func ExpectListPostsWithAuthor(results []ListPostsWithAuthorRow, err error) Step {
	return Step{
		SQL:  listPostsWithAuthor,
		Args: nil,
		Apply: func(q Query) error {
			q.(*ListPostsWithAuthorQuery).SetResults(results)
			return err
		},
	}
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, status, description, created_at FROM users
ORDER BY created_at DESC
`

type ListUsersQuery struct {
	ex      QueryExecutor
	Results []User
}

func (q *ListUsersQuery) SQL() string {
	return listUsers
}

func (q *ListUsersQuery) Args() []any {
	return nil
}

func (q *ListUsersQuery) ScanRow(row pgx.Row) error {
	var i User
	if err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
	); err != nil {
		return err
	}
	q.Results = append(q.Results, i)
	return nil
}

func (q *ListUsersQuery) SetResults(results []User) {
	q.Results = results
}

func (q *ListUsersQuery) Eval(ctx context.Context) ([]User, error) {
	q.Results = nil
	if err := q.ex.Execute(ctx, q); err != nil {
		return nil, err
	}
	return q.Results, nil
}

func NewListUsersQuery(ex QueryExecutor) *ListUsersQuery {
	return &ListUsersQuery{ex: ex}
}
func ExpectListUsers(results []User, err error) Step {
	return Step{
		SQL:  listUsers,
		Args: nil,
		Apply: func(q Query) error {
			q.(*ListUsersQuery).SetResults(results)
			return err
		},
	}
}

const updateUserEmail = `-- name: UpdateUserEmail :execrows
UPDATE users
SET email = $2
WHERE id = $1
`

type UpdateUserEmailQuery struct {
	ex           QueryExecutor
	iD           int64
	email        string
	RowsAffected int64
}

func (q *UpdateUserEmailQuery) SQL() string {
	return updateUserEmail
}

func (q *UpdateUserEmailQuery) Args() []any {
	return []any{q.iD, q.email}
}

func (q *UpdateUserEmailQuery) SetRowsAffected(n int64) {
	q.RowsAffected = n
}

func (q *UpdateUserEmailQuery) Eval(ctx context.Context, iD int64, email string) (int64, error) {
	q.iD = iD
	q.email = email
	if err := q.ex.Execute(ctx, q); err != nil {
		return 0, err
	}
	return q.RowsAffected, nil
}

func NewUpdateUserEmailQuery(ex QueryExecutor) *UpdateUserEmailQuery {
	return &UpdateUserEmailQuery{ex: ex}
}
func ExpectUpdateUserEmail(iD int64, email string, rowsAffected int64, err error) Step {
	return Step{
		SQL:  updateUserEmail,
		Args: []any{iD, email},
		Apply: func(q Query) error {
			q.(*UpdateUserEmailQuery).SetRowsAffected(rowsAffected)
			return err
		},
	}
}
