// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package queries

import (
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/sqlc-dev/sqlc-gen-go/examples/pgx-split-packages/db"
	"github.com/sqlc-dev/sqlc-gen-go/examples/pgx-split-packages/models"
)

const countAccounts = `-- name: CountAccounts :one
SELECT COUNT(*) FROM accounts
`

func CountAccounts() db.Query[int64] {
	return db.NewStatement(countAccounts).One(db.ScanValue[int64])
}

const countPosts = `-- name: CountPosts :one
SELECT COUNT(*) FROM posts
`

func CountPosts() db.Query[int64] {
	return db.NewStatement(countPosts).One(db.ScanValue[int64])
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (username, email, role, status)
VALUES ($1, $2, $3, $4)
RETURNING id, username, email, role, status, created_at, updated_at
`

type CreateAccountParams struct {
	Username string               `json:"username"`
	Email    string               `json:"email"`
	Role     models.UserRole      `json:"role"`
	Status   models.AccountStatus `json:"status"`
}

func CreateAccount(arg CreateAccountParams) db.Query[models.Account] {
	return db.NewStatement(createAccount, arg.Username, arg.Email, arg.Role, arg.Status).One(scanAccount)
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (account_id, title, content, published)
VALUES ($1, $2, $3, $4)
RETURNING id, account_id, title, content, published, created_at
`

type CreatePostParams struct {
	AccountID int64  `json:"account_id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	Published bool   `json:"published"`
}

func CreatePost(arg CreatePostParams) db.Query[models.Post] {
	return db.NewStatement(createPost, arg.AccountID, arg.Title, arg.Content, arg.Published).One(scanPost)
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts
WHERE id = $1
`

func DeleteAccount(id int64) db.Query[int64] {
	return db.NewStatement(deleteAccount, id).Exec()
}

const getAccount = `-- name: GetAccount :one
SELECT id, username, email, role, status, created_at, updated_at FROM accounts
WHERE id = $1
`

func GetAccount(id int64) db.Query[models.Account] {
	return db.NewStatement(getAccount, id).One(scanAccount)
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT id, username, email, role, status, created_at, updated_at FROM accounts
WHERE username = $1
`

func GetAccountByUsername(username string) db.Query[models.Account] {
	return db.NewStatement(getAccountByUsername, username).One(scanAccount)
}

const getPost = `-- name: GetPost :one
SELECT p.id, p.account_id, p.title, p.content, p.published, p.created_at, a.username, a.role
FROM posts p
JOIN accounts a ON p.account_id = a.id
WHERE p.id = $1
`

type GetPostRow struct {
	ID        int64              `json:"id"`
	AccountID int64              `json:"account_id"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	Published bool               `json:"published"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Username  string             `json:"username"`
	Role      models.UserRole    `json:"role"`
}

func GetPost(id int64) db.Query[GetPostRow] {
	return db.NewStatement(getPost, id).One(scanGetPostRow)
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, username, email, role, status, created_at, updated_at FROM accounts
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

func ListAccounts(limit int32, offset int32) db.Query[[]models.Account] {
	return db.NewStatement(listAccounts, limit, offset).Many(scanAccount)
}

const listAccountsByRole = `-- name: ListAccountsByRole :many
SELECT id, username, email, role, status, created_at, updated_at FROM accounts
WHERE role = $1
ORDER BY created_at DESC
`

func ListAccountsByRole(role models.UserRole) db.Query[[]models.Account] {
	return db.NewStatement(listAccountsByRole, role).Many(scanAccount)
}

const listPostsByAccount = `-- name: ListPostsByAccount :many
SELECT id, account_id, title, content, published, created_at FROM posts
WHERE account_id = $1
ORDER BY created_at DESC
`

func ListPostsByAccount(accountID int64) db.Query[[]models.Post] {
	return db.NewStatement(listPostsByAccount, accountID).Many(scanPost)
}

const publishPost = `-- name: PublishPost :execrows
UPDATE posts
SET published = true
WHERE id = $1 AND published = false
`

func PublishPost(id int64) db.Query[int64] {
	return db.NewStatement(publishPost, id).Exec()
}

const updateAccountStatus = `-- name: UpdateAccountStatus :execrows
UPDATE accounts
SET status = $2, updated_at = NOW()
WHERE id = $1
`

func UpdateAccountStatus(iD int64, status models.AccountStatus) db.Query[int64] {
	return db.NewStatement(updateAccountStatus, iD, status).Exec()
}

func scanAccount(row pgx.Row) (models.Account, error) {
	var i models.Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

func scanPost(row pgx.Row) (models.Post, error) {
	var i models.Post
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Title,
		&i.Content,
		&i.Published,
		&i.CreatedAt,
	)
	return i, err
}

func scanGetPostRow(row pgx.Row) (GetPostRow, error) {
	var i GetPostRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Title,
		&i.Content,
		&i.Published,
		&i.CreatedAt,
		&i.Username,
		&i.Role,
	)
	return i, err
}
