// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/sqlc-dev/sqlc-gen-go/examples/pgx-split-packages/db"
	"github.com/sqlc-dev/sqlc-gen-go/examples/pgx-split-packages/models"
)

const countAccounts = `-- name: CountAccounts :one
SELECT COUNT(*) FROM accounts
`

type CountAccountsQuery struct {
	ex     db.QueryExecutor
	Result int64
}

func (q *CountAccountsQuery) SQL() string {
	return countAccounts
}

func (q *CountAccountsQuery) Args() []any {
	return nil
}

func (q *CountAccountsQuery) Scan(row pgx.Row) error {
	return row.Scan(&q.Result)
}

func (q *CountAccountsQuery) SetResult(result int64) {
	q.Result = result
}
func (q *CountAccountsQuery) Eval(ctx context.Context) (int64, error) {
	if err := q.ex.Execute(ctx, q); err != nil {
		var zero int64
		return zero, err
	}
	return q.Result, nil
}

func NewCountAccountsQuery(ex db.QueryExecutor) *CountAccountsQuery {
	return &CountAccountsQuery{ex: ex}
}
func ExpectCountAccounts(result int64, err error) db.Step {
	return db.Step{
		SQL:  countAccounts,
		Args: nil,
		Apply: func(q db.Query) error {
			q.(*CountAccountsQuery).SetResult(result)
			return err
		},
	}
}

const countPosts = `-- name: CountPosts :one
SELECT COUNT(*) FROM posts
`

type CountPostsQuery struct {
	ex     db.QueryExecutor
	Result int64
}

func (q *CountPostsQuery) SQL() string {
	return countPosts
}

func (q *CountPostsQuery) Args() []any {
	return nil
}

func (q *CountPostsQuery) Scan(row pgx.Row) error {
	return row.Scan(&q.Result)
}

func (q *CountPostsQuery) SetResult(result int64) {
	q.Result = result
}
func (q *CountPostsQuery) Eval(ctx context.Context) (int64, error) {
	if err := q.ex.Execute(ctx, q); err != nil {
		var zero int64
		return zero, err
	}
	return q.Result, nil
}

func NewCountPostsQuery(ex db.QueryExecutor) *CountPostsQuery {
	return &CountPostsQuery{ex: ex}
}
func ExpectCountPosts(result int64, err error) db.Step {
	return db.Step{
		SQL:  countPosts,
		Args: nil,
		Apply: func(q db.Query) error {
			q.(*CountPostsQuery).SetResult(result)
			return err
		},
	}
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (username, email, role, status)
VALUES ($1, $2, $3, $4)
RETURNING id, username, email, role, status, created_at, updated_at
`

type CreateAccountParams struct {
	Username string               `json:"username"`
	Email    string               `json:"email"`
	Role     models.UserRole      `json:"role"`
	Status   models.AccountStatus `json:"status"`
}

type CreateAccountQuery struct {
	ex     db.QueryExecutor
	arg    CreateAccountParams
	Result models.Account
}

func (q *CreateAccountQuery) SQL() string {
	return createAccount
}

func (q *CreateAccountQuery) Args() []any {
	return []any{q.arg.Username, q.arg.Email, q.arg.Role, q.arg.Status}
}

func (q *CreateAccountQuery) Scan(row pgx.Row) error {
	return row.Scan(
		&q.Result.ID,
		&q.Result.Username,
		&q.Result.Email,
		&q.Result.Role,
		&q.Result.Status,
		&q.Result.CreatedAt,
		&q.Result.UpdatedAt,
	)
}

func (q *CreateAccountQuery) SetResult(result models.Account) {
	q.Result = result
}
func (q *CreateAccountQuery) Eval(ctx context.Context, arg CreateAccountParams) (models.Account, error) {
	q.arg = arg
	if err := q.ex.Execute(ctx, q); err != nil {
		var zero models.Account
		return zero, err
	}
	return q.Result, nil
}

func NewCreateAccountQuery(ex db.QueryExecutor) *CreateAccountQuery {
	return &CreateAccountQuery{ex: ex}
}
func ExpectCreateAccount(arg CreateAccountParams, result models.Account, err error) db.Step {
	return db.Step{
		SQL:  createAccount,
		Args: []any{arg.Username, arg.Email, arg.Role, arg.Status},
		Apply: func(q db.Query) error {
			q.(*CreateAccountQuery).SetResult(result)
			return err
		},
	}
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (account_id, title, content, published)
VALUES ($1, $2, $3, $4)
RETURNING id, account_id, title, content, published, created_at
`

type CreatePostParams struct {
	AccountID int64  `json:"account_id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	Published bool   `json:"published"`
}

type CreatePostQuery struct {
	ex     db.QueryExecutor
	arg    CreatePostParams
	Result models.Post
}

func (q *CreatePostQuery) SQL() string {
	return createPost
}

func (q *CreatePostQuery) Args() []any {
	return []any{q.arg.AccountID, q.arg.Title, q.arg.Content, q.arg.Published}
}

func (q *CreatePostQuery) Scan(row pgx.Row) error {
	return row.Scan(
		&q.Result.ID,
		&q.Result.AccountID,
		&q.Result.Title,
		&q.Result.Content,
		&q.Result.Published,
		&q.Result.CreatedAt,
	)
}

func (q *CreatePostQuery) SetResult(result models.Post) {
	q.Result = result
}
func (q *CreatePostQuery) Eval(ctx context.Context, arg CreatePostParams) (models.Post, error) {
	q.arg = arg
	if err := q.ex.Execute(ctx, q); err != nil {
		var zero models.Post
		return zero, err
	}
	return q.Result, nil
}

func NewCreatePostQuery(ex db.QueryExecutor) *CreatePostQuery {
	return &CreatePostQuery{ex: ex}
}
func ExpectCreatePost(arg CreatePostParams, result models.Post, err error) db.Step {
	return db.Step{
		SQL:  createPost,
		Args: []any{arg.AccountID, arg.Title, arg.Content, arg.Published},
		Apply: func(q db.Query) error {
			q.(*CreatePostQuery).SetResult(result)
			return err
		},
	}
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts
WHERE id = $1
`

type DeleteAccountQuery struct {
	ex           db.QueryExecutor
	id           int64
	RowsAffected int64
}

func (q *DeleteAccountQuery) SQL() string {
	return deleteAccount
}

func (q *DeleteAccountQuery) Args() []any {
	return []any{q.id}
}

func (q *DeleteAccountQuery) SetRowsAffected(n int64) {
	q.RowsAffected = n
}
func (q *DeleteAccountQuery) Eval(ctx context.Context, id int64) error {
	q.id = id
	return q.ex.Execute(ctx, q)
}

func NewDeleteAccountQuery(ex db.QueryExecutor) *DeleteAccountQuery {
	return &DeleteAccountQuery{ex: ex}
}
func ExpectDeleteAccount(id int64, err error) db.Step {
	return db.Step{
		SQL:  deleteAccount,
		Args: []any{id},
		Apply: func(q db.Query) error {
			return err
		},
	}
}

const getAccount = `-- name: GetAccount :one
SELECT id, username, email, role, status, created_at, updated_at FROM accounts
WHERE id = $1
`

type GetAccountQuery struct {
	ex     db.QueryExecutor
	id     int64
	Result models.Account
}

func (q *GetAccountQuery) SQL() string {
	return getAccount
}

func (q *GetAccountQuery) Args() []any {
	return []any{q.id}
}

func (q *GetAccountQuery) Scan(row pgx.Row) error {
	return row.Scan(
		&q.Result.ID,
		&q.Result.Username,
		&q.Result.Email,
		&q.Result.Role,
		&q.Result.Status,
		&q.Result.CreatedAt,
		&q.Result.UpdatedAt,
	)
}

func (q *GetAccountQuery) SetResult(result models.Account) {
	q.Result = result
}
func (q *GetAccountQuery) Eval(ctx context.Context, id int64) (models.Account, error) {
	q.id = id
	if err := q.ex.Execute(ctx, q); err != nil {
		var zero models.Account
		return zero, err
	}
	return q.Result, nil
}

func NewGetAccountQuery(ex db.QueryExecutor) *GetAccountQuery {
	return &GetAccountQuery{ex: ex}
}
func ExpectGetAccount(id int64, result models.Account, err error) db.Step {
	return db.Step{
		SQL:  getAccount,
		Args: []any{id},
		Apply: func(q db.Query) error {
			q.(*GetAccountQuery).SetResult(result)
			return err
		},
	}
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT id, username, email, role, status, created_at, updated_at FROM accounts
WHERE username = $1
`

type GetAccountByUsernameQuery struct {
	ex       db.QueryExecutor
	username string
	Result   models.Account
}

func (q *GetAccountByUsernameQuery) SQL() string {
	return getAccountByUsername
}

func (q *GetAccountByUsernameQuery) Args() []any {
	return []any{q.username}
}

func (q *GetAccountByUsernameQuery) Scan(row pgx.Row) error {
	return row.Scan(
		&q.Result.ID,
		&q.Result.Username,
		&q.Result.Email,
		&q.Result.Role,
		&q.Result.Status,
		&q.Result.CreatedAt,
		&q.Result.UpdatedAt,
	)
}

func (q *GetAccountByUsernameQuery) SetResult(result models.Account) {
	q.Result = result
}
func (q *GetAccountByUsernameQuery) Eval(ctx context.Context, username string) (models.Account, error) {
	q.username = username
	if err := q.ex.Execute(ctx, q); err != nil {
		var zero models.Account
		return zero, err
	}
	return q.Result, nil
}

func NewGetAccountByUsernameQuery(ex db.QueryExecutor) *GetAccountByUsernameQuery {
	return &GetAccountByUsernameQuery{ex: ex}
}
func ExpectGetAccountByUsername(username string, result models.Account, err error) db.Step {
	return db.Step{
		SQL:  getAccountByUsername,
		Args: []any{username},
		Apply: func(q db.Query) error {
			q.(*GetAccountByUsernameQuery).SetResult(result)
			return err
		},
	}
}

const getPost = `-- name: GetPost :one
SELECT p.id, p.account_id, p.title, p.content, p.published, p.created_at, a.username, a.role
FROM posts p
JOIN accounts a ON p.account_id = a.id
WHERE p.id = $1
`

type GetPostRow struct {
	ID        int64              `json:"id"`
	AccountID int64              `json:"account_id"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	Published bool               `json:"published"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Username  string             `json:"username"`
	Role      models.UserRole    `json:"role"`
}

type GetPostQuery struct {
	ex     db.QueryExecutor
	id     int64
	Result GetPostRow
}

func (q *GetPostQuery) SQL() string {
	return getPost
}

func (q *GetPostQuery) Args() []any {
	return []any{q.id}
}

func (q *GetPostQuery) Scan(row pgx.Row) error {
	return row.Scan(
		&q.Result.ID,
		&q.Result.AccountID,
		&q.Result.Title,
		&q.Result.Content,
		&q.Result.Published,
		&q.Result.CreatedAt,
		&q.Result.Username,
		&q.Result.Role,
	)
}

func (q *GetPostQuery) SetResult(result GetPostRow) {
	q.Result = result
}
func (q *GetPostQuery) Eval(ctx context.Context, id int64) (GetPostRow, error) {
	q.id = id
	if err := q.ex.Execute(ctx, q); err != nil {
		var zero GetPostRow
		return zero, err
	}
	return q.Result, nil
}

func NewGetPostQuery(ex db.QueryExecutor) *GetPostQuery {
	return &GetPostQuery{ex: ex}
}
func ExpectGetPost(id int64, result GetPostRow, err error) db.Step {
	return db.Step{
		SQL:  getPost,
		Args: []any{id},
		Apply: func(q db.Query) error {
			q.(*GetPostQuery).SetResult(result)
			return err
		},
	}
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, username, email, role, status, created_at, updated_at FROM accounts
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAccountsQuery struct {
	ex      db.QueryExecutor
	limit   int32
	offset  int32
	Results []models.Account
}

func (q *ListAccountsQuery) SQL() string {
	return listAccounts
}

func (q *ListAccountsQuery) Args() []any {
	return []any{q.limit, q.offset}
}

func (q *ListAccountsQuery) ScanRow(row pgx.Row) error {
	var i models.Account
	if err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	); err != nil {
		return err
	}
	q.Results = append(q.Results, i)
	return nil
}

func (q *ListAccountsQuery) SetResults(results []models.Account) {
	q.Results = results
}

func (q *ListAccountsQuery) Eval(ctx context.Context, limit int32, offset int32) ([]models.Account, error) {
	q.limit = limit
	q.offset = offset
	q.Results = nil
	if err := q.ex.Execute(ctx, q); err != nil {
		return nil, err
	}
	return q.Results, nil
}

func NewListAccountsQuery(ex db.QueryExecutor) *ListAccountsQuery {
	return &ListAccountsQuery{ex: ex}
}
func ExpectListAccounts(limit int32, offset int32, results []models.Account, err error) db.Step {
	return db.Step{
		SQL:  listAccounts,
		Args: []any{limit, offset},
		Apply: func(q db.Query) error {
			q.(*ListAccountsQuery).SetResults(results)
			return err
		},
	}
}

const listAccountsByRole = `-- name: ListAccountsByRole :many
SELECT id, username, email, role, status, created_at, updated_at FROM accounts
WHERE role = $1
ORDER BY created_at DESC
`

type ListAccountsByRoleQuery struct {
	ex      db.QueryExecutor
	role    models.UserRole
	Results []models.Account
}

func (q *ListAccountsByRoleQuery) SQL() string {
	return listAccountsByRole
}

func (q *ListAccountsByRoleQuery) Args() []any {
	return []any{q.role}
}

func (q *ListAccountsByRoleQuery) ScanRow(row pgx.Row) error {
	var i models.Account
	if err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	); err != nil {
		return err
	}
	q.Results = append(q.Results, i)
	return nil
}

func (q *ListAccountsByRoleQuery) SetResults(results []models.Account) {
	q.Results = results
}

func (q *ListAccountsByRoleQuery) Eval(ctx context.Context, role models.UserRole) ([]models.Account, error) {
	q.role = role
	q.Results = nil
	if err := q.ex.Execute(ctx, q); err != nil {
		return nil, err
	}
	return q.Results, nil
}

func NewListAccountsByRoleQuery(ex db.QueryExecutor) *ListAccountsByRoleQuery {
	return &ListAccountsByRoleQuery{ex: ex}
}
func ExpectListAccountsByRole(role models.UserRole, results []models.Account, err error) db.Step {
	return db.Step{
		SQL:  listAccountsByRole,
		Args: []any{role},
		Apply: func(q db.Query) error {
			q.(*ListAccountsByRoleQuery).SetResults(results)
			return err
		},
	}
}

const listPostsByAccount = `-- name: ListPostsByAccount :many
SELECT id, account_id, title, content, published, created_at FROM posts
WHERE account_id = $1
ORDER BY created_at DESC
`

type ListPostsByAccountQuery struct {
	ex        db.QueryExecutor
	accountID int64
	Results   []models.Post
}

func (q *ListPostsByAccountQuery) SQL() string {
	return listPostsByAccount
}

func (q *ListPostsByAccountQuery) Args() []any {
	return []any{q.accountID}
}

func (q *ListPostsByAccountQuery) ScanRow(row pgx.Row) error {
	var i models.Post
	if err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Title,
		&i.Content,
		&i.Published,
		&i.CreatedAt,
	); err != nil {
		return err
	}
	q.Results = append(q.Results, i)
	return nil
}

func (q *ListPostsByAccountQuery) SetResults(results []models.Post) {
	q.Results = results
}

func (q *ListPostsByAccountQuery) Eval(ctx context.Context, accountID int64) ([]models.Post, error) {
	q.accountID = accountID
	q.Results = nil
	if err := q.ex.Execute(ctx, q); err != nil {
		return nil, err
	}
	return q.Results, nil
}

func NewListPostsByAccountQuery(ex db.QueryExecutor) *ListPostsByAccountQuery {
	return &ListPostsByAccountQuery{ex: ex}
}
func ExpectListPostsByAccount(accountID int64, results []models.Post, err error) db.Step {
	return db.Step{
		SQL:  listPostsByAccount,
		Args: []any{accountID},
		Apply: func(q db.Query) error {
			q.(*ListPostsByAccountQuery).SetResults(results)
			return err
		},
	}
}

const publishPost = `-- name: PublishPost :execrows
UPDATE posts
SET published = true
WHERE id = $1 AND published = false
`

type PublishPostQuery struct {
	ex           db.QueryExecutor
	id           int64
	RowsAffected int64
}

func (q *PublishPostQuery) SQL() string {
	return publishPost
}

func (q *PublishPostQuery) Args() []any {
	return []any{q.id}
}

func (q *PublishPostQuery) SetRowsAffected(n int64) {
	q.RowsAffected = n
}

func (q *PublishPostQuery) Eval(ctx context.Context, id int64) (int64, error) {
	q.id = id
	if err := q.ex.Execute(ctx, q); err != nil {
		return 0, err
	}
	return q.RowsAffected, nil
}

func NewPublishPostQuery(ex db.QueryExecutor) *PublishPostQuery {
	return &PublishPostQuery{ex: ex}
}
func ExpectPublishPost(id int64, rowsAffected int64, err error) db.Step {
	return db.Step{
		SQL:  publishPost,
		Args: []any{id},
		Apply: func(q db.Query) error {
			q.(*PublishPostQuery).SetRowsAffected(rowsAffected)
			return err
		},
	}
}

const updateAccountStatus = `-- name: UpdateAccountStatus :execrows
UPDATE accounts
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateAccountStatusQuery struct {
	ex           db.QueryExecutor
	iD           int64
	status       models.AccountStatus
	RowsAffected int64
}

func (q *UpdateAccountStatusQuery) SQL() string {
	return updateAccountStatus
}

func (q *UpdateAccountStatusQuery) Args() []any {
	return []any{q.iD, q.status}
}

func (q *UpdateAccountStatusQuery) SetRowsAffected(n int64) {
	q.RowsAffected = n
}

func (q *UpdateAccountStatusQuery) Eval(ctx context.Context, iD int64, status models.AccountStatus) (int64, error) {
	q.iD = iD
	q.status = status
	if err := q.ex.Execute(ctx, q); err != nil {
		return 0, err
	}
	return q.RowsAffected, nil
}

func NewUpdateAccountStatusQuery(ex db.QueryExecutor) *UpdateAccountStatusQuery {
	return &UpdateAccountStatusQuery{ex: ex}
}
func ExpectUpdateAccountStatus(iD int64, status models.AccountStatus, rowsAffected int64, err error) db.Step {
	return db.Step{
		SQL:  updateAccountStatus,
		Args: []any{iD, status},
		Apply: func(q db.Query) error {
			q.(*UpdateAccountStatusQuery).SetRowsAffected(rowsAffected)
			return err
		},
	}
}
