// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"github.com/jackc/pgx/v5"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email) VALUES ($1, $2) RETURNING id, name, email
`

type CreateUserParams struct {
	Name  string
	Email string
}

func CreateUser(arg CreateUserParams) Query[User] {
	return NewStatement(createUser, arg.Name, arg.Email).One(scanUser)
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

func DeleteUser(id int64) Query[int64] {
	return NewStatement(deleteUser, id).Exec()
}

const getUser = `-- name: GetUser :one
SELECT id, name, email FROM users WHERE id = $1
`

func GetUser(id int64) Query[User] {
	return NewStatement(getUser, id).One(scanUser)
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email FROM users ORDER BY id
`

func ListUsers() Query[[]User] {
	return NewStatement(listUsers).Many(scanUser)
}

func scanUser(row pgx.Row) (User, error) {
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}
