// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email) VALUES ($1, $2) RETURNING id, name, email
`

type CreateUserParams struct {
	Name  string
	Email string
}

type CreateUserQuery struct {
	ex     QueryExecutor
	arg    CreateUserParams
	Result User
}

func (q *CreateUserQuery) SQL() string {
	return createUser
}

func (q *CreateUserQuery) Args() []any {
	return []any{q.arg.Name, q.arg.Email}
}

func (q *CreateUserQuery) Scan(row pgx.Row) error {
	return row.Scan(&q.Result.ID, &q.Result.Name, &q.Result.Email)
}

func (q *CreateUserQuery) SetResult(result User) {
	q.Result = result
}
func (q *CreateUserQuery) Eval(ctx context.Context, arg CreateUserParams) (User, error) {
	q.arg = arg
	if err := q.ex.Execute(ctx, q); err != nil {
		var zero User
		return zero, err
	}
	return q.Result, nil
}

func NewCreateUserQuery(ex QueryExecutor) *CreateUserQuery {
	return &CreateUserQuery{ex: ex}
}
func ExpectCreateUser(arg CreateUserParams, result User, err error) Step {
	return Step{
		SQL:  createUser,
		Args: []any{arg.Name, arg.Email},
		Apply: func(q Query) error {
			q.(*CreateUserQuery).SetResult(result)
			return err
		},
	}
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

type DeleteUserQuery struct {
	ex           QueryExecutor
	id           int64
	RowsAffected int64
}

func (q *DeleteUserQuery) SQL() string {
	return deleteUser
}

func (q *DeleteUserQuery) Args() []any {
	return []any{q.id}
}

func (q *DeleteUserQuery) SetRowsAffected(n int64) {
	q.RowsAffected = n
}

func (q *DeleteUserQuery) Eval(ctx context.Context, id int64) (int64, error) {
	q.id = id
	if err := q.ex.Execute(ctx, q); err != nil {
		return 0, err
	}
	return q.RowsAffected, nil
}

func NewDeleteUserQuery(ex QueryExecutor) *DeleteUserQuery {
	return &DeleteUserQuery{ex: ex}
}
func ExpectDeleteUser(id int64, rowsAffected int64, err error) Step {
	return Step{
		SQL:  deleteUser,
		Args: []any{id},
		Apply: func(q Query) error {
			q.(*DeleteUserQuery).SetRowsAffected(rowsAffected)
			return err
		},
	}
}

const getUser = `-- name: GetUser :one
SELECT id, name, email FROM users WHERE id = $1
`

type GetUserQuery struct {
	ex     QueryExecutor
	id     int64
	Result User
}

func (q *GetUserQuery) SQL() string {
	return getUser
}

func (q *GetUserQuery) Args() []any {
	return []any{q.id}
}

func (q *GetUserQuery) Scan(row pgx.Row) error {
	return row.Scan(&q.Result.ID, &q.Result.Name, &q.Result.Email)
}

func (q *GetUserQuery) SetResult(result User) {
	q.Result = result
}
func (q *GetUserQuery) Eval(ctx context.Context, id int64) (User, error) {
	q.id = id
	if err := q.ex.Execute(ctx, q); err != nil {
		var zero User
		return zero, err
	}
	return q.Result, nil
}

func NewGetUserQuery(ex QueryExecutor) *GetUserQuery {
	return &GetUserQuery{ex: ex}
}
func ExpectGetUser(id int64, result User, err error) Step {
	return Step{
		SQL:  getUser,
		Args: []any{id},
		Apply: func(q Query) error {
			q.(*GetUserQuery).SetResult(result)
			return err
		},
	}
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email FROM users ORDER BY id
`

type ListUsersQuery struct {
	ex      QueryExecutor
	Results []User
}

func (q *ListUsersQuery) SQL() string {
	return listUsers
}

func (q *ListUsersQuery) Args() []any {
	return nil
}

func (q *ListUsersQuery) ScanRow(row pgx.Row) error {
	var i User
	if err := row.Scan(&i.ID, &i.Name, &i.Email); err != nil {
		return err
	}
	q.Results = append(q.Results, i)
	return nil
}

func (q *ListUsersQuery) SetResults(results []User) {
	q.Results = results
}

func (q *ListUsersQuery) Eval(ctx context.Context) ([]User, error) {
	q.Results = nil
	if err := q.ex.Execute(ctx, q); err != nil {
		return nil, err
	}
	return q.Results, nil
}

func NewListUsersQuery(ex QueryExecutor) *ListUsersQuery {
	return &ListUsersQuery{ex: ex}
}
func ExpectListUsers(results []User, err error) Step {
	return Step{
		SQL:  listUsers,
		Args: nil,
		Apply: func(q Query) error {
			q.(*ListUsersQuery).SetResults(results)
			return err
		},
	}
}
