// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

type DBTXWithTx interface {
	DBTX
	BeginTx(context.Context, *sql.TxOptions) (*sql.Tx, error)
}

// Query produces T. Generated queries implement it; so can user-defined ones.
type Query[T any] interface {
	SQL() string
	Args() []any
	Do(ctx context.Context, db DBTX) (T, error)
}

// ExecFunc runs a query on db and returns its result.
type ExecFunc func(ctx context.Context, db DBTX) (any, error)

// QueryExecutor executes queries
type QueryExecutor interface {
	Execute(ctx context.Context, sql string, args []any, do ExecFunc) (any, error)
	WithTx(ctx context.Context, fn func(QueryExecutor) error) error
}

// DB runs typed queries on a QueryExecutor.
type DB struct {
	ex QueryExecutor
}

func New(ex QueryExecutor) DB {
	return DB{ex: ex}
}

func (d DB) Run[T any](ctx context.Context, q Query[T]) (T, error) {
	var zero T
	v, err := d.ex.Execute(ctx, q.SQL(), q.Args(), func(ctx context.Context, db DBTX) (any, error) {
		return q.Do(ctx, db)
	})
	if err != nil {
		return zero, err
	}
	if v == nil {
		return zero, nil
	}
	t, ok := v.(T)
	if !ok {
		return zero, fmt.Errorf("expected result type %T, got %T", zero, v)
	}
	return t, nil
}

// WithTx executes a function within a transaction
func (d DB) WithTx(ctx context.Context, fn func(DB) error) error {
	return d.ex.WithTx(ctx, func(tx QueryExecutor) error {
		return fn(DB{ex: tx})
	})
}

// Row is satisfied by *sql.Row and *sql.Rows.
type Row interface {
	Scan(dest ...any) error
}

type RowScanner[T any] func(Row) (T, error)

func ScanValue[T any](row Row) (T, error) {
	var v T
	err := row.Scan(&v)
	return v, err
}

// Statement is SQL with its arguments; One, Many, Exec, ExecResult and ExecLastID turn it into a Query.
type Statement struct {
	sql  string
	args []any
}

func NewStatement(sql string, args ...any) Statement {
	return Statement{sql: sql, args: args}
}

func (s Statement) SQL() string { return s.sql }
func (s Statement) Args() []any { return s.args }

func (s Statement) One[T any](scan RowScanner[T]) Query[T] {
	return oneQuery[T]{s, scan}
}

func (s Statement) Many[T any](scan RowScanner[T]) Query[[]T] {
	return manyQuery[T]{s, scan}
}

func (s Statement) Exec() Query[int64] {
	return execQuery{s}
}

func (s Statement) ExecResult() Query[sql.Result] {
	return execResultQuery{s}
}

func (s Statement) ExecLastID() Query[int64] {
	return execLastIDQuery{s}
}

type oneQuery[T any] struct {
	Statement
	scan RowScanner[T]
}

func (q oneQuery[T]) Do(ctx context.Context, db DBTX) (T, error) {
	return q.scan(db.QueryRowContext(ctx, q.sql, q.args...))
}

type manyQuery[T any] struct {
	Statement
	scan RowScanner[T]
}

func (q manyQuery[T]) Do(ctx context.Context, db DBTX) ([]T, error) {
	rows, err := db.QueryContext(ctx, q.sql, q.args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []T
	for rows.Next() {
		v, err := q.scan(rows)
		if err != nil {
			return nil, err
		}
		items = append(items, v)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type execQuery struct {
	Statement
}

func (q execQuery) Do(ctx context.Context, db DBTX) (int64, error) {
	result, err := db.ExecContext(ctx, q.sql, q.args...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

type execResultQuery struct {
	Statement
}

func (q execResultQuery) Do(ctx context.Context, db DBTX) (sql.Result, error) {
	return db.ExecContext(ctx, q.sql, q.args...)
}

type execLastIDQuery struct {
	Statement
}

func (q execLastIDQuery) Do(ctx context.Context, db DBTX) (int64, error) {
	result, err := db.ExecContext(ctx, q.sql, q.args...)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

// Executor implements QueryExecutor using DBTX
type Executor struct {
	db       DBTX
	dbWithTx DBTXWithTx
}

// NewExecutor creates a new Executor
func NewExecutor(db DBTX) *Executor {
	dbWithTx, _ := db.(DBTXWithTx)
	return &Executor{
		db:       db,
		dbWithTx: dbWithTx,
	}
}

// WithTx executes a function within a transaction
func (e *Executor) WithTx(ctx context.Context, fn func(QueryExecutor) error) error {
	if e.dbWithTx == nil {
		return fmt.Errorf("database does not support transactions")
	}

	tx, err := e.dbWithTx.BeginTx(ctx, nil)
	if err != nil {
		return err
	}

	executor := NewExecutor(tx)

	if err := fn(executor); err != nil {
		if rbErr := tx.Rollback(); rbErr != nil {
			return fmt.Errorf("tx failed: %w, rollback failed: %v", err, rbErr)
		}
		return err
	}

	return tx.Commit()
}

func (e *Executor) Execute(ctx context.Context, sql string, args []any, do ExecFunc) (any, error) {
	return do(ctx, e.db)
}

// Compile-time interface checks
var (
	_ DBTX       = (*sql.DB)(nil)
	_ DBTX       = (*sql.Conn)(nil)
	_ DBTX       = (*sql.Tx)(nil)
	_ DBTXWithTx = (*sql.DB)(nil)
	_ DBTXWithTx = (*sql.Conn)(nil)
)

type Step struct {
	SQL    string
	Args   []any
	Result any
	Err    error
}

// Expect builds a Step matching q's SQL and Args that yields result and err.
func Expect[T any](q Query[T], result T, err error) Step {
	return Step{SQL: q.SQL(), Args: q.Args(), Result: result, Err: err}
}

// StubExecutor verifies queries are executed in expected order with expected arguments.
type StubExecutor struct {
	t interface {
		Helper()
		Errorf(format string, args ...any)
	}
	steps []Step
	i     int
}

func NewStubExecutor(t interface {
	Helper()
	Errorf(format string, args ...any)
}, steps ...Step) *StubExecutor {
	return &StubExecutor{t: t, steps: steps}
}

func (s *StubExecutor) Execute(ctx context.Context, sql string, args []any, do ExecFunc) (any, error) {
	s.t.Helper()

	if s.i >= len(s.steps) {
		s.t.Errorf("unexpected query: SQL=%q Args=%v", sql, args)
		return nil, fmt.Errorf("unexpected query")
	}

	step := s.steps[s.i]
	s.i++

	if sql != step.SQL {
		s.t.Errorf("SQL mismatch at step %d:\nwant: %q\ngot:  %q", s.i, step.SQL, sql)
		return nil, fmt.Errorf("SQL mismatch")
	}

	if !reflect.DeepEqual(args, step.Args) {
		s.t.Errorf("Args mismatch at step %d:\nwant: %v\ngot:  %v", s.i, step.Args, args)
		return nil, fmt.Errorf("args mismatch")
	}

	return step.Result, step.Err
}

func (s *StubExecutor) AssertDone() {
	s.t.Helper()
	if s.i != len(s.steps) {
		s.t.Errorf("not all steps executed: %d/%d", s.i, len(s.steps))
	}
}

func (s *StubExecutor) WithTx(ctx context.Context, fn func(QueryExecutor) error) error {
	return fn(s)
}

var _ QueryExecutor = (*StubExecutor)(nil)
