// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"database/sql"
	"strings"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func CountUsers() Query[int64] {
	return NewStatement(countUsers).One(ScanValue[int64])
}

const countUsersByIDsExceptName = `-- name: CountUsersByIDsExceptName :one
SELECT COUNT(*) FROM users WHERE name <> ?1 AND id IN (/*SLICE:ids*/?)
`

func CountUsersByIDsExceptName(name string, ids []int64) Query[int64] {
	query := countUsersByIDsExceptName
	var queryParams []any
	queryParams = append(queryParams, name)
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	return NewStatement(query, queryParams...).One(ScanValue[int64])
}

const countUsersByNameOrEmail = `-- name: CountUsersByNameOrEmail :one
SELECT COUNT(*) FROM users WHERE name = ?1 OR email = ?1
`

func CountUsersByNameOrEmail(value string) Query[int64] {
	return NewStatement(countUsersByNameOrEmail, value).One(ScanValue[int64])
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (author_id, title, body)
VALUES (?, ?, ?)
RETURNING id, author_id, title, body, created_at
`

type CreatePostParams struct {
	AuthorID int64  `json:"author_id"`
	Title    string `json:"title"`
	Body     string `json:"body"`
}

func CreatePost(arg CreatePostParams) Query[Post] {
	return NewStatement(createPost, arg.AuthorID, arg.Title, arg.Body).One(scanPost)
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email)
VALUES (?, ?)
RETURNING id, name, email, created_at
`

func CreateUser(name string, email string) Query[User] {
	return NewStatement(createUser, name, email).One(scanUser)
}

const createUserGetID = `-- name: CreateUserGetID :execlastid
INSERT INTO users (name, email)
VALUES (?, ?)
`

func CreateUserGetID(name string, email string) Query[int64] {
	return NewStatement(createUserGetID, name, email).ExecLastID()
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = ?
`

func DeleteUser(id int64) Query[int64] {
	return NewStatement(deleteUser, id).Exec()
}

const getPostWithAuthor = `-- name: GetPostWithAuthor :one
SELECT posts.id, posts.author_id, posts.title, posts.body, posts.created_at, users.id, users.name, users.email, users.created_at
FROM posts
JOIN users ON users.id = posts.author_id
WHERE posts.id = ?
`

type GetPostWithAuthorRow struct {
	Post Post `json:"post"`
	User User `json:"user"`
}

func GetPostWithAuthor(id int64) Query[GetPostWithAuthorRow] {
	return NewStatement(getPostWithAuthor, id).One(scanGetPostWithAuthorRow)
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, created_at FROM users
WHERE id = ?
`

func GetUser(id int64) Query[User] {
	return NewStatement(getUser, id).One(scanUser)
}

const listPostsWithAuthor = `-- name: ListPostsWithAuthor :many
SELECT posts.id, posts.author_id, posts.title, posts.body, posts.created_at, users.id, users.name, users.email, users.created_at
FROM posts
JOIN users ON users.id = posts.author_id
ORDER BY posts.created_at DESC
`

type ListPostsWithAuthorRow struct {
	Post Post `json:"post"`
	User User `json:"user"`
}

func ListPostsWithAuthor() Query[[]ListPostsWithAuthorRow] {
	return NewStatement(listPostsWithAuthor).Many(scanListPostsWithAuthorRow)
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, created_at FROM users
ORDER BY created_at DESC
`

func ListUsers() Query[[]User] {
	return NewStatement(listUsers).Many(scanUser)
}

const listUsersByIDs = `-- name: ListUsersByIDs :many
SELECT id, name, email, created_at FROM users WHERE id IN (/*SLICE:ids*/?) ORDER BY id
`

func ListUsersByIDs(ids []int64) Query[[]User] {
	query := listUsersByIDs
	var queryParams []any
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	return NewStatement(query, queryParams...).Many(scanUser)
}

const updateUserEmail = `-- name: UpdateUserEmail :execrows
UPDATE users
SET email = ?
WHERE id = ?
`

func UpdateUserEmail(email string, iD int64) Query[int64] {
	return NewStatement(updateUserEmail, email, iD).Exec()
}

const updateUserName = `-- name: UpdateUserName :execresult
UPDATE users
SET name = ?
WHERE id = ?
`

func UpdateUserName(name string, iD int64) Query[sql.Result] {
	return NewStatement(updateUserName, name, iD).ExecResult()
}

func scanPost(row Row) (Post, error) {
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

func scanUser(row Row) (User, error) {
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

func scanGetPostWithAuthorRow(row Row) (GetPostWithAuthorRow, error) {
	var i GetPostWithAuthorRow
	err := row.Scan(
		&i.Post.ID,
		&i.Post.AuthorID,
		&i.Post.Title,
		&i.Post.Body,
		&i.Post.CreatedAt,
		&i.User.ID,
		&i.User.Name,
		&i.User.Email,
		&i.User.CreatedAt,
	)
	return i, err
}

func scanListPostsWithAuthorRow(row Row) (ListPostsWithAuthorRow, error) {
	var i ListPostsWithAuthorRow
	err := row.Scan(
		&i.Post.ID,
		&i.Post.AuthorID,
		&i.Post.Title,
		&i.Post.Body,
		&i.Post.CreatedAt,
		&i.User.ID,
		&i.User.Name,
		&i.User.Email,
		&i.User.CreatedAt,
	)
	return i, err
}
