// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v4"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const batchGetUsers = `-- name: BatchGetUsers :batchone
SELECT id, name, email, created_at FROM users
WHERE id = $1
`

type batchGetUsersBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type batchGetUsersQuery struct {
	args []int64
}

func (q batchGetUsersQuery) SQL() string { return batchGetUsers }
func (q batchGetUsersQuery) Args() []any { return nil }

func (q batchGetUsersQuery) Do(ctx context.Context, db DBTX) (*batchGetUsersBatchResults, error) {
	batch := &pgx.Batch{}
	for _, a := range q.args {
		vals := []any{
			a,
		}
		batch.Queue(batchGetUsers, vals...)
	}
	br := db.SendBatch(ctx, batch)
	return &batchGetUsersBatchResults{br, len(q.args), false}, nil
}

func BatchGetUsers(id []int64) Query[*batchGetUsersBatchResults] {
	return batchGetUsersQuery{args: id}
}

func (b *batchGetUsersBatchResults) QueryRow(f func(int, User, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i User
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *batchGetUsersBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const batchInsertUsers = `-- name: BatchInsertUsers :batchexec
INSERT INTO users (name, email)
VALUES ($1, $2)
`

type batchInsertUsersBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchInsertUsersParams struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type batchInsertUsersQuery struct {
	args []BatchInsertUsersParams
}

func (q batchInsertUsersQuery) SQL() string { return batchInsertUsers }
func (q batchInsertUsersQuery) Args() []any { return nil }

func (q batchInsertUsersQuery) Do(ctx context.Context, db DBTX) (*batchInsertUsersBatchResults, error) {
	batch := &pgx.Batch{}
	for _, a := range q.args {
		vals := []any{
			a.Name,
			a.Email,
		}
		batch.Queue(batchInsertUsers, vals...)
	}
	br := db.SendBatch(ctx, batch)
	return &batchInsertUsersBatchResults{br, len(q.args), false}, nil
}

func BatchInsertUsers(arg []BatchInsertUsersParams) Query[*batchInsertUsersBatchResults] {
	return batchInsertUsersQuery{args: arg}
}

func (b *batchInsertUsersBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *batchInsertUsersBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const batchListUsersByEmail = `-- name: BatchListUsersByEmail :batchmany
SELECT id, name, email, created_at FROM users
WHERE email LIKE $1
`

type batchListUsersByEmailBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type batchListUsersByEmailQuery struct {
	args []string
}

func (q batchListUsersByEmailQuery) SQL() string { return batchListUsersByEmail }
func (q batchListUsersByEmailQuery) Args() []any { return nil }

func (q batchListUsersByEmailQuery) Do(ctx context.Context, db DBTX) (*batchListUsersByEmailBatchResults, error) {
	batch := &pgx.Batch{}
	for _, a := range q.args {
		vals := []any{
			a,
		}
		batch.Queue(batchListUsersByEmail, vals...)
	}
	br := db.SendBatch(ctx, batch)
	return &batchListUsersByEmailBatchResults{br, len(q.args), false}, nil
}

func BatchListUsersByEmail(email []string) Query[*batchListUsersByEmailBatchResults] {
	return batchListUsersByEmailQuery{args: email}
}

func (b *batchListUsersByEmailBatchResults) Query(f func(int, []User, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var items []User
		if b.closed {
			if f != nil {
				f(t, items, ErrBatchAlreadyClosed)
			}
			continue
		}
		err := func() error {
			rows, err := b.br.Query()
			if err != nil {
				return err
			}
			defer rows.Close()
			for rows.Next() {
				var i User
				if err := rows.Scan(
					&i.ID,
					&i.Name,
					&i.Email,
					&i.CreatedAt,
				); err != nil {
					return err
				}
				items = append(items, i)
			}
			return rows.Err()
		}()
		if f != nil {
			f(t, items, err)
		}
	}
}

func (b *batchListUsersByEmailBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const batchUpdateEmails = `-- name: BatchUpdateEmails :batchexec
UPDATE users
SET email = $2
WHERE id = $1
`

type batchUpdateEmailsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchUpdateEmailsParams struct {
	ID    int64  `json:"id"`
	Email string `json:"email"`
}

type batchUpdateEmailsQuery struct {
	args []BatchUpdateEmailsParams
}

func (q batchUpdateEmailsQuery) SQL() string { return batchUpdateEmails }
func (q batchUpdateEmailsQuery) Args() []any { return nil }

func (q batchUpdateEmailsQuery) Do(ctx context.Context, db DBTX) (*batchUpdateEmailsBatchResults, error) {
	batch := &pgx.Batch{}
	for _, a := range q.args {
		vals := []any{
			a.ID,
			a.Email,
		}
		batch.Queue(batchUpdateEmails, vals...)
	}
	br := db.SendBatch(ctx, batch)
	return &batchUpdateEmailsBatchResults{br, len(q.args), false}, nil
}

func BatchUpdateEmails(arg []BatchUpdateEmailsParams) Query[*batchUpdateEmailsBatchResults] {
	return batchUpdateEmailsQuery{args: arg}
}

func (b *batchUpdateEmailsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *batchUpdateEmailsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
