// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"github.com/jackc/pgx/v4"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func CountUsers() Query[int64] {
	return NewStatement(countUsers).One(ScanValue[int64])
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (author_id, title, body)
VALUES ($1, $2, $3)
RETURNING id, author_id, title, body, created_at
`

type CreatePostParams struct {
	AuthorID int64  `json:"author_id"`
	Title    string `json:"title"`
	Body     string `json:"body"`
}

func CreatePost(arg CreatePostParams) Query[Post] {
	return NewStatement(createPost, arg.AuthorID, arg.Title, arg.Body).One(scanPost)
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email)
VALUES ($1, $2)
RETURNING id, name, email, created_at
`

func CreateUser(name string, email string) Query[User] {
	return NewStatement(createUser, name, email).One(scanUser)
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func DeleteUser(id int64) Query[int64] {
	return NewStatement(deleteUser, id).Exec()
}

const getPostWithAuthor = `-- name: GetPostWithAuthor :one
SELECT posts.id, posts.author_id, posts.title, posts.body, posts.created_at, users.id, users.name, users.email, users.created_at
FROM posts
JOIN users ON users.id = posts.author_id
WHERE posts.id = $1
`

type GetPostWithAuthorRow struct {
	Post Post `json:"post"`
	User User `json:"user"`
}

func GetPostWithAuthor(id int64) Query[GetPostWithAuthorRow] {
	return NewStatement(getPostWithAuthor, id).One(scanGetPostWithAuthorRow)
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, created_at FROM users
WHERE id = $1
`

func GetUser(id int64) Query[User] {
	return NewStatement(getUser, id).One(scanUser)
}

const getUserForUpdate = `-- name: GetUserForUpdate :one
SELECT id, name, email, created_at FROM users
WHERE id = $1
FOR UPDATE
`

func GetUserForUpdate(id int64) Query[User] {
	return NewStatement(getUserForUpdate, id).One(scanUser)
}

const listPostsWithAuthor = `-- name: ListPostsWithAuthor :many
SELECT posts.id, posts.author_id, posts.title, posts.body, posts.created_at, users.id, users.name, users.email, users.created_at
FROM posts
JOIN users ON users.id = posts.author_id
ORDER BY posts.created_at DESC
`

type ListPostsWithAuthorRow struct {
	Post Post `json:"post"`
	User User `json:"user"`
}

func ListPostsWithAuthor() Query[[]ListPostsWithAuthorRow] {
	return NewStatement(listPostsWithAuthor).Many(scanListPostsWithAuthorRow)
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, created_at FROM users
ORDER BY created_at DESC
`

func ListUsers() Query[[]User] {
	return NewStatement(listUsers).Many(scanUser)
}

const updateUserEmail = `-- name: UpdateUserEmail :execrows
UPDATE users
SET email = $2
WHERE id = $1
`

func UpdateUserEmail(iD int64, email string) Query[int64] {
	return NewStatement(updateUserEmail, iD, email).Exec()
}

func scanPost(row pgx.Row) (Post, error) {
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

func scanUser(row pgx.Row) (User, error) {
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

func scanGetPostWithAuthorRow(row pgx.Row) (GetPostWithAuthorRow, error) {
	var i GetPostWithAuthorRow
	err := row.Scan(
		&i.Post.ID,
		&i.Post.AuthorID,
		&i.Post.Title,
		&i.Post.Body,
		&i.Post.CreatedAt,
		&i.User.ID,
		&i.User.Name,
		&i.User.Email,
		&i.User.CreatedAt,
	)
	return i, err
}

func scanListPostsWithAuthorRow(row pgx.Row) (ListPostsWithAuthorRow, error) {
	var i ListPostsWithAuthorRow
	err := row.Scan(
		&i.Post.ID,
		&i.Post.AuthorID,
		&i.Post.Title,
		&i.Post.Body,
		&i.Post.CreatedAt,
		&i.User.ID,
		&i.User.Name,
		&i.User.Email,
		&i.User.CreatedAt,
	)
	return i, err
}
